language: php

sudo: false

php:
    - 5.2
    - 5.6

env:
    - WP_VERSION=master WP_MULTISITE=0 WPDB_DRIVER=mysql
    - WP_VERSION=4.3 WP_MULTISITE=0 WPDB_DRIVER=mysql
    - WP_VERSION=4.2 WP_MULTISITE=0 WPDB_DRIVER=mysql
    - WP_VERSION=4.1 WP_MULTISITE=0 WPDB_DRIVER=mysql
    - WP_VERSION=master WP_MULTISITE=0 WPDB_DRIVER=mysqli
    - WP_VERSION=4.3 WP_MULTISITE=0 WPDB_DRIVER=mysqli
    - WP_VERSION=4.2 WP_MULTISITE=0 WPDB_DRIVER=mysqli
    - WP_VERSION=4.1 WP_MULTISITE=0 WPDB_DRIVER=mysqli
    - WP_VERSION=master WP_MULTISITE=0 WPDB_DRIVER=pdo_mysql
    - WP_VERSION=4.3 WP_MULTISITE=0 WPDB_DRIVER=pdo_mysql
    - WP_VERSION=4.2 WP_MULTISITE=0 WPDB_DRIVER=pdo_mysql
    - WP_VERSION=4.1 WP_MULTISITE=0 WPDB_DRIVER=pdo_mysql

matrix:
    allow_failures:
        - env: WP_VERSION=4.1 WP_MULTISITE=0 WPDB_DRIVER=mysql
        - env: WP_VERSION=4.1 WP_MULTISITE=0 WPDB_DRIVER=mysqli
        - env: WP_VERSION=4.1 WP_MULTISITE=0 WPDB_DRIVER=pdo_mysql

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION $WP_MULTISITE $WPDB_DRIVER

script:
    - cd /tmp/wordpress
    - phpunit --group wpdb
